project:
  type: website

website:
  title: "Quan Phung"
  favicon: "lee.png"
  reader-mode: true
  back-to-top-navigation: true
  page-navigation: true
  search: true
  navbar:
    logo: "lcat.png"
    background: dark
    foreground: info
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
  sidebar:
    style: "docked"
    background: dark
    foreground: info
    border: true
    contents:
      - section: "Posts"
        contents:
          - href: posts/Card Shuffling/shuffle.qmd
  page-footer:
    border: true
    background: dark
    foreground: info
    left: "Copyright 2024, Quan Phung"
    right:
      - icon: github
        href: https://github.com/ldlinn
      - icon: discord
        href: https://discord.com/users/quaned
      - icon: facebook
        href: https://www.facebook.com/quanphung.1603
      - icon: instagram
        href: https://www.instagram.com/quanphung.1603/
      - icon: envelope
        href: mailto:youremail@gmail.com

format:
  html:
    theme: assets/dark.scss

editor: visual

filters:
  - posts/Card Shuffling/environment.lua

execute:
  freeze: auto